version : '3'

volumes:
  postgres_data:
      driver: local

services:
  DBPay:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sh:/docker-entrypoint-initdb.d/init_database.sh
    environment:
      POSTGRES_DB: payment
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment
      PGPORT : 5432
    ports:
      - '5432:5432'
    network_mode : "host"
  gunicorn:
    build: .
    command: gunicorn server.PaymentService:app -b :5000
    restart: always    
    environment:
      PYTHONUNBUFFERED: 'true'
    ports:
      - '5000:5000'
    expose:
      - "5000"
    depends_on:
      - DBPay
    network_mode: "host"
